spring.application.name=lunfy-server

# ???? ??????
spring.datasource.url=jdbc:postgresql://localhost:5432/lunfy
spring.datasource.username=postgres
spring.datasource.password=OBi1mzLwmeWMS!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
jwt.secret=akujsfghasufaysfgqyusfqgsfyuqqofysqagf1768gfhsajfgashjfgasjhfg
jwt.expiration=86400000

# AES
aes.secret=lunfy-aes-key-16